"""initial schema

Baseline revision representing the full schema as of this refactor (all tables, matching
app.models exactly). Two things both had to be true for this file, and the first draft
only got one of them right:

1. On a genuinely fresh/empty database, upgrade() must create every table - this is
   what makes `alembic upgrade head` work for a new clone.
2. On the already-populated live database (which reached this exact schema over several
   earlier ALTER TABLE-based migrations, before Alembic existed in this project), this
   revision must be stamp-able without re-running anything: `alembic stamp head` marks
   the database as already being at this revision without executing upgrade() at all.

(The first version of this file was generated by autogenerate diffing directly against
the live database, which already matched app.models - that produced an empty upgrade(),
which stamped the live DB fine but silently created zero tables for anyone starting
fresh. Regenerated by diffing against an empty database instead, then applied to the
live DB via stamp - not upgrade - so no data was touched.)

Revision ID: f8b4f610f463
Revises:
Create Date: 2026-08-14 15:23:39.354847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b4f610f463'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuing_body', sa.String(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('sectors', sa.Text(), nullable=True),
    sa.Column('capabilities_summary', sa.Text(), nullable=True),
    sa.Column('geographic_reach', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imap_email', sa.String(), nullable=True),
    sa.Column('imap_app_password', sa.String(), nullable=True),
    sa.Column('sender_filter', sa.String(), nullable=True),
    sa.Column('sender_denylist', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_summary', sa.Text(), nullable=True),
    sa.Column('notify_email', sa.String(), nullable=True),
    sa.Column('notify_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('contract_value_bdt', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('scope_of_work', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('was_tender', sa.Boolean(), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tender_ref', sa.String(), nullable=True),
    sa.Column('source_email_message_id', sa.String(), nullable=True),
    sa.Column('notice_url', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('document_price', sa.String(), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('eligibility_requirements', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('hard_filter_pass', sa.Boolean(), nullable=True),
    sa.Column('hard_filter_reason', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_reasons', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_tender_ref'), 'tenders', ['tender_ref'], unique=True)
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('usage_log')
    op.drop_index(op.f('ix_tenders_tender_ref'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('processed_emails')
    op.drop_table('past_contracts')
    op.drop_table('email_settings')
    op.drop_table('company_profile')
    op.drop_table('certifications')
