/* The records themselves, and loading/saving them. Everything else reads from here.
   Moved verbatim from Bhumijo_Proposal_Tracker_22Jul2026.html — 6 function(s), not rewritten.
   Loaded in a fixed order by index.html, sharing one scope, exactly as before. */

const SEED = [
  {id:'s0',entity:'P&D',title:'Single family duplex House Design',category:'Proposal',client:'Dr, Akter House (chadpur)',openDate:'2026-06-28',closeDate:'2026-07-18',status:'Yet to be submitted',result:'',responsible:'Masud Sir',contract:'',remark:'050726_we are going to do a visit at client place need to follow up. company profile is already shared',value:'',startDate:'',endDate:''},
  {id:'s1',entity:'P&D',title:'Interior Design of male and female room',category:'RFP',client:'IUB',openDate:'2026-07-05',closeDate:'2026-07-15',status:'Submitted',result:'Waiting for Result',responsible:'Amenul and Aorchita',contract:'',remark:'15072026_Proposal submitted | 050726_participated in pre bid meeting. Need to submit technical and financial report with BOQ including VAT and AIT',value:'',startDate:'',endDate:''},
  {id:'s2',entity:'P&D',title:'The Executive Kitchen (Malibagh Branch)',category:'Proposal',client:'',openDate:'2026-06-22',closeDate:'2026-07-10',status:'Yet to be submitted',result:'',responsible:'Masud Sir',contract:'',remark:'050726_Need to do a service contract, construction at actual and design fee based on project cost in discussion with client. need to send design and proposal',value:'',startDate:'',endDate:''},
  {id:'s3',entity:'P&D',title:'Interior Work at Jolshiri area',category:'',client:'Major General Dr. Shameem Haider',openDate:'2026-05-22',closeDate:'2026-06-30',status:'Drop',result:'',responsible:'Amenul',contract:'',remark:'110626_client visited chez de sofia to get an idea of interior work. need to take him another visit at banani DOHS. Also need to share a propsal file for apartment interior work | 070626_ client want to visit our place, probable visit date will be shared by client | Need to do initial meeting.',value:'',startDate:'',endDate:''},
  {id:'s4',entity:'P&D',title:'20 story Building at Rangpur',category:'',client:'Dr. Dipu',openDate:'2026-05-22',closeDate:'2026-07-17',status:'Yet to be submitted',result:'',responsible:'Amenul & Masud Sir',contract:'',remark:'Need to conduct initial meeting at july 15th (2026)',value:'',startDate:'',endDate:''},
  {id:'s5',entity:'P&D',title:'House at Savar',category:'',client:'Mr. Maksud (planner)',openDate:'2026-06-01',closeDate:'2026-06-30',status:'Yet to be submitted',result:'',responsible:'Farhana Ma\'am',contract:'',remark:'Follow up Farhana Apu. Need time to get feedback',value:'',startDate:'',endDate:''},
  {id:'s6',entity:'P&D',title:'Road beautification',category:'',client:'DSCC',openDate:'2026-06-21',closeDate:'2026-06-30',status:'Yet to be submitted',result:'',responsible:'Monir',contract:'',remark:'Premilineary design need to share with regulatory body to discuss and find scope of work',value:'',startDate:'',endDate:''},
  {id:'s7',entity:'P&D',title:'Ai automated Poltry Building/Design',category:'',client:'Paragon Group',openDate:'2026-06-08',closeDate:'2026-08-31',status:'Yet to be submitted',result:'',responsible:'Sobuj, Amenul and Masud Sir',contract:'',remark:'18072026_ Existing farm was visited by Masud Sir, will do a internal meeting after that we will submit our proposal to MD sir | 130726_ need to send the revised proposal with technical point | 270626_Sobuj bhai is working on project plan and preparing guidline to share with client | 210626_need to collect information of project size and their concept model. to share the proposal or to share scope of work | meeting on 15th June 2026 at 11am',value:'',startDate:'',endDate:''},
  {id:'s8',entity:'P&D',title:'Interior Work at Mirpur area (Nashid House)',category:'Proposal & Work',client:'Mr. Hasib Hasnat',openDate:'2026-05-22',closeDate:'2026-07-16',status:'Submitted',result:'Waiting for Result',responsible:'Amenul & Monir',contract:'',remark:'160626_primary budget and plan was given to client and then based on client feedback a 3d design was given for further review purpose | 140626_Ask monir bhai about document submission | (Work in progress) | Immediate proposal submission and work need to start ASAP | 070626_ we will charge only cost. Not for profit.',value:'',startDate:'',endDate:''},
  {id:'s9',entity:'P&D',title:'Residens for Mrs Shahnaz.  (Uttara)',category:'',client:'',openDate:'2026-06-01',closeDate:'2026-06-17',status:'Drop',result:'Rejected',responsible:'Amenul and Aorchita',contract:'',remark:'070726_client has budget issue. for now she may not require the service | 050726_Client wants to talk with Masud Bhai | 240626_Final proposal has been shared with client. waiting for client feedback | 140626_follow up Aorchita to prepare and submit the final proposal | 100626_ Had a meeting a with Client. We will visit her premises on 14th June to assess the place for final proposal | Check meeting note for direction. | 070626_ need to do a NDA ASAP, and facebook bosting ASAP',value:'',startDate:'',endDate:''},
  {id:'s10',entity:'P&D',title:'Vacation house at sylhet',category:'',client:'Mr. Foysal',openDate:'2026-06-01',closeDate:'2026-06-11',status:'Submitted',result:'Waiting for Result',responsible:'Farhana Ma\'am, Amenul',contract:'',remark:'130626_will do a final follow up to get client feedback | waiting for customer response. client is sourcing other vendors | 110626_proposal submitted | 070626_follow up sobuj/monir for pricing. Target to send the file by 10th June | Need to conduct initial meeting.',value:'',startDate:'',endDate:''},
  {id:'s11',entity:'P&D',title:'Urban Planning Survey and Studies for "Formulation of Strategic Plan of Dhaka Peripheral Region"',category:'EOI -> RFP -> Presentation -> Got the Project',client:'UDD',openDate:'2026-01-14',closeDate:'2026-06-10',status:'Submitted',result:'Accepted',responsible:'Khairul',contract:'No',remark:'Got the project. (JV with IWM, DevCon, SARM)',value:'',startDate:'',endDate:''},
  {id:'s12',entity:'P&D',title:'Request For Quotation (RFQ) For Interior Work at Tejgaon Existing Priority Premises Under The Tejgaon Branch, Dhaka',category:'RFP for  Interior Design',client:'Prime Bank',openDate:'',closeDate:'2026-06-09',status:'Drop',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s13',entity:'P&D',title:'Preparation of Strategic Plan for Munshiganj District',category:'EOI -> RFP -> Presentation -> Got the Project',client:'UDD',openDate:'2026-02-27',closeDate:'2026-06-08',status:'Submitted',result:'Accepted',responsible:'Khairul',contract:'No',remark:'with Tiller - Decode - Bhumijo - SurvCon JV',value:'',startDate:'',endDate:''},
  {id:'s14',entity:'P&D',title:'Construction of a 250-Bed General Hospital',category:'RFP for building design',client:'DSK',openDate:'2026-04-26',closeDate:'2026-05-17',status:'Submitted',result:'Waiting for Result',responsible:'Khairul',contract:'',remark:'JV with DCON | Director (Health), Dushtha Shasthya Kendra (DSK) | Email: mrahman@dskbangladesh.org | Phone: 01776 762272',value:'',startDate:'',endDate:''},
  {id:'s15',entity:'P&D',title:'Gov official residence at bosila',category:'',client:'',openDate:'',closeDate:'2026-05-05',status:'Drop',result:'Waiting for Result',responsible:'Farhana ma\'am & Sobuj & Amenul',contract:'',remark:'client has sold their land. | waiting for customer response | Send proposal after discussion with farhana',value:'',startDate:'',endDate:''},
  {id:'s16',entity:'P&D',title:'Preparation of Strategic Plan for Barishal Metropolitan Area',category:'EOI -> RFP -> Presentation -> Rejected',client:'UDD',openDate:'',closeDate:'2026-05-03',status:'Submitted',result:'Rejected',responsible:'Khairul',contract:'',remark:'with Tiller - BCL - Bhumijo - SurvCon JV | Winner: BETS',value:'',startDate:'',endDate:''},
  {id:'s17',entity:'P&D',title:'Mr Mintu residence (Bnanani biswas ref)',category:'Proposal',client:'',openDate:'',closeDate:'2026-05-03',status:'Yet to be submitted',result:'',responsible:'Masud Sir',contract:'',remark:'280626_client will visit our premises for a meeting. expected date 30th June 2026 | Send proposal after discussion with masud',value:'',startDate:'',endDate:''},
  {id:'s18',entity:'P&D',title:'Bogura Shapla park project',category:'',client:'R & H',openDate:'',closeDate:'2026-05-02',status:'Yet to be submitted',result:'',responsible:'Masud',contract:'',remark:'Talk to R&H exien Bgura',value:'',startDate:'',endDate:''},
  {id:'s19',entity:'P&D',title:'Survey and Data creation in Kushtia Pauroshava for implementation of Integrated Municipal Information System (IMIS)',category:'EOI',client:'Kushtia Pauroshava',openDate:'2026-03-28',closeDate:'2026-04-13',status:'Submitted',result:'Rejected',responsible:'Khairul',contract:'',remark:'JV with eSolve',value:'',startDate:'',endDate:''},
  {id:'s20',entity:'P&D',title:'Providing Consultancy Service for Architectural, Structural, Electro- Mechanical, Plumbing Design, Cost Estimation etc. and full-time construction supervision for the construction of the Female Hall w',category:'eGP (Tender ID: 1222663), EOI -> RFP',client:'Dhaka University',openDate:'2026-02-25',closeDate:'2026-03-09',status:'Submitted',result:'Waiting for Result',responsible:'Khairul',contract:'',remark:'DCON-FORMATION-BHUMIJO JV (for DU package 2), we established a | systematic design (3D perspective plan for 3 home tutor hall)',value:'',startDate:'',endDate:''},
  {id:'s21',entity:'P&D',title:'Architectural, Master Planning & Engineering Consultancy Services for Nursing College Project – Hobiganj, Sylhet',category:'RFP',client:'Sajeda Doundation',openDate:'2026-02-18',closeDate:'2026-03-04',status:'Submitted',result:'Rejected',responsible:'Khairul',contract:'',remark:'mostafa.aquib@sajida.org, 01725522308, JV with Archytas',value:'',startDate:'',endDate:''},
  {id:'s22',entity:'P&D',title:'“স্বচ্ছ”, Comfortable, hygienic and smart public sanitation for low-income community',category:'RFP for Toilet',client:'JTI',openDate:'2025-12-17',closeDate:'2026-01-19',status:'Submitted',result:'Accepted',responsible:'Sabuj',contract:'Yes',remark:'',value:'',startDate:'',endDate:''},
  {id:'s23',entity:'P&D',title:'Renovation of BCC Male and Female Washroom and Tiles work at Ground Floor, Level-1, Level-4, Level-5, Level-8, Level-10 & Level-12.',category:'eGP (Tender ID: 1199337), EOI',client:'ICT Ministry',openDate:'',closeDate:'2026-01-12',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with M/S J.S ENTERPRISE',value:'',startDate:'',endDate:''},
  {id:'s24',entity:'P&D',title:'Scoping Private Sector Participation in Municipal WSS in Bangladesh (procurement number: 0002020260)',category:'EOI (Online)',client:'World Bank',openDate:'',closeDate:'2026-01-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Enroute International',value:'',startDate:'',endDate:''},
  {id:'s25',entity:'P&D',title:'Proposal for Sustainable Operation and Maintenance of 126 Public Toilets Under DPHE',category:'Consultancy proposal',client:'DPHE',openDate:'',closeDate:'2025-12-14',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s26',entity:'P&D',title:'5-storied Rasidential Building Design at Rangpur',category:'Proposal for building design',client:'Md. Ashraf Hossain',openDate:'',closeDate:'2025-11-16',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s27',entity:'P&D',title:'83498394- Design of small-scale construction measures with option of construction supervision',category:'RFP for Design & Supervision',client:'GIZ',openDate:'',closeDate:'2025-10-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Link',value:'',startDate:'',endDate:''},
  {id:'s28',entity:'P&D',title:'Interior Construction Works for Dhaka Power Distribution Company Limited (DPDC)',category:'Proposal for interior',client:'TBEA',openDate:'',closeDate:'2025-09-14',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'"Archytas Limited & Bhumijo Limited JV" fixed name for whole project',value:'',startDate:'',endDate:''},
  {id:'s29',entity:'P&D',title:'Development of a Climate Resilient WASH Design Manual',category:'EOI for Toilet',client:'WaterAid',openDate:'',closeDate:'2025-09-11',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s30',entity:'P&D',title:'Sanitation Improvement for School Girls',category:'RFP for Toilet',client:'Prime Bank',openDate:'',closeDate:'2025-08-29',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s31',entity:'P&D',title:'GIZ include project: Climate-smart Urban Development in Bangladesh',category:'EOI for Research',client:'GIZ',openDate:'',closeDate:'2025-07-30',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with MDF',value:'',startDate:'',endDate:''},
  {id:'s32',entity:'P&D',title:'Feasibility study for the Project "Further Extension & Development of Begum Rokeya University, Rangpur',category:'e-GP_EOI for Buidling Design',client:'Begum Rokeya University',openDate:'',closeDate:'2025-07-24',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s33',entity:'P&D',title:'ADISIYA Holding Limited - Jolshiri Project',category:'Proposal for building design',client:'Ehsanul Hoque & Kamrujjaman',openDate:'',closeDate:'2025-07-16',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s34',entity:'P&D',title:'Assessment and Schematic Restoration Plan of VP and Khas Ponds under RAJUK Area',category:'EOI for Park Public Space',client:'RAJUK',openDate:'',closeDate:'2025-06-30',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with CEGIS',value:'',startDate:'',endDate:''},
  {id:'s35',entity:'P&D',title:'Consultancy Services for Design and Supervision of Five-Storied Student Dormitory Building Including a Semi Basement at 12 Katha Uttara Land of IUB',category:'RFP for building design',client:'IUB',openDate:'',closeDate:'2025-05-27',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s36',entity:'P&D',title:'A Collaborative Approach to Reconstruct the Toilets of Dhaka and Narayanganj Courts',category:'RFP for Toilet',client:'BRAC',openDate:'',closeDate:'2025-05-26',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'2nd phase ongoing',value:'',startDate:'',endDate:''},
  {id:'s37',entity:'P&D',title:'Water, Sanitation and Hygiene Initiative',category:'RFP for Toilet',client:'Metlife',openDate:'',closeDate:'2025-04-16',status:'Submitted',result:'',responsible:'',contract:'',remark:'Proposal revised and resubmitted',value:'',startDate:'',endDate:''},
  {id:'s38',entity:'P&D',title:'Consultancy Services for the Preparation of Architectural, Structural, & MEP Design of a G+4 multi-storied residential building at Babukha, Sadar, Rangpur',category:'Proposal for building design',client:'Md Mominul Islam',openDate:'',closeDate:'2025-04-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s39',entity:'P&D',title:'Bicycle Parking and Associate Service Provision at Dhaka Metro Station (Sustainable and Affordable Bicycle Service for Urban Mobility)',category:'Proposal for Grant',client:'BRAC _ MRT',openDate:'',closeDate:'2025-03-08',status:'Submitted',result:'',responsible:'',contract:'',remark:'JV with UNDP',value:'',startDate:'',endDate:''},
  {id:'s40',entity:'P&D',title:'Consultancy Services for the Preparation of Architectural, Structural, & MEP Design of a G+2 multi-storied residential building at Textile Mor, Rangpur',category:'Proposal for building design',client:'Md Zakiul Hasan',openDate:'',closeDate:'2025-03-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s41',entity:'P&D',title:'W-PHASE Bangladesh – Waterborne PFAS & Human Health Assessment for Sustainable Environments',category:'EOI for Research',client:'KSP Norway',openDate:'',closeDate:'2025-02-25',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s42',entity:'P&D',title:'Selection & Employment of Asset Management, Operation and Maintenance and Place Management Consultancy Firm (Package DCNUP/S-03-A)- National)',category:'RFP for Urban Planning & Development',client:'DSCC_ World bank',openDate:'',closeDate:'2025-02-24',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'JV with Enroute',value:'',startDate:'',endDate:''},
  {id:'s43',entity:'P&D',title:'Effluent Treatment Plant (ETP) Design and Drawing for Magura Paper Mills Ltd. at Narayanganj',category:'Proposal for ETP',client:'Magura Paper Mills Ltd',openDate:'',closeDate:'2024-10-15',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s44',entity:'P&D',title:'Proposed Renovation Plan for Three Toilet Block of Supreme Court Main Building',category:'RFP for Toilet',client:'BRAC',openDate:'',closeDate:'2024-09-14',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s45',entity:'P&D',title:'Consultancy Services for Design & Top Supervision for Total Improvement of Paris Canal & Mitigation of Waterlogging at Adjacent Areas',category:'RFP for park public space',client:'DNCC',openDate:'',closeDate:'2024-08-04',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s46',entity:'P&D',title:'Design the comprehensive and economically viable green WASH model along with detailed landscaping of Shaheed A.H.M. Kamaruzzaman Central Park & Zoo, Rajshahi',category:'RFP for Toilet',client:'WaterAid',openDate:'',closeDate:'2024-07-14',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s47',entity:'P&D',title:'Consulting Firm For Performing of Landscape design works of Sonali Bank Officer’s Quarter, Uttara-Dhaka',category:'EOI for landscape design',client:'Sonali Bank PLC., Uttara',openDate:'',closeDate:'2024-06-02',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with IDS & ASSOCIATES',value:'',startDate:'',endDate:''},
  {id:'s48',entity:'P&D',title:'Consulting Firm For Performing Of Inerior Re-Modeling And Renovation Design Works Of Sonali Bank Plc, Local Office, Motijheel-Dhaka',category:'EOI for interior design',client:'Sonali Bank PLC., Motijheel',openDate:'',closeDate:'2024-05-30',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with IDS & ASSOCIATES',value:'',startDate:'',endDate:''},
  {id:'s49',entity:'P&D',title:'Proposal for Existing building assessment and fire safety plan for Jakir Super Market, BB road Narayanganj',category:'Proposal for consultancy',client:'Jakir Hossain',openDate:'',closeDate:'2024-05-27',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s50',entity:'P&D',title:'Asgor proposal',category:'',client:'',openDate:'',closeDate:'2024-05-09',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s51',entity:'P&D',title:'Understanding toilet usage patterns in Bangladesh and develop hygienic and standardized practices for different provisions and facilities',category:'RFP for Research_Sanitation',client:'Wateraid',openDate:'',closeDate:'2024-05-06',status:'Submitted',result:'',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s52',entity:'P&D',title:'Public Service Integration Plan for Dhaka North Elevated Expressway\'s Kuril Segment',category:'RFP for park public space',client:'DNCC',openDate:'',closeDate:'2024-05-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Sheltech',value:'',startDate:'',endDate:''},
  {id:'s53',entity:'P&D',title:'Consultancy service for CHEZ DE SOFIA Rooftop Re-design & Renovation Works',category:'Proposal for interior',client:'Mr. Javed Zaman',openDate:'',closeDate:'2024-04-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s54',entity:'P&D',title:'Feasibility Study with Conceptual Design, Cost Estimation & Draft DPP preparation for Development of ‘Children’s Park & Playground’ at Kalshi Balur Math under Dhaka North City Corporation (DNCC), Dhak',category:'RFP for park public space',client:'DNCC',openDate:'',closeDate:'2024-03-28',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with CUS',value:'',startDate:'',endDate:''},
  {id:'s55',entity:'P&D',title:'Consultancy Services for The Project of Proposed 10 storied multi-functional SOS building having 8000-10000 sft per floor approximately.',category:'EOI for building design',client:'Tripto Neer Foundation',openDate:'',closeDate:'2024-03-20',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s56',entity:'P&D',title:'Consultancy service for Enhancing the Interior Design and Décor of Bhumijo Office',category:'Proposal for interior',client:'Bhumijo Limited',openDate:'',closeDate:'2024-03-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s57',entity:'P&D',title:'Consultancy service for CHEZ DE SOFIA Ground Floor Lounge and Landscape Renovation Works',category:'Proposal for interior',client:'Mr. Javed Zaman',openDate:'',closeDate:'2024-02-25',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s58',entity:'P&D',title:'Green, Resilient, and Integrated Nayaranganj Project (GRIN Project)',category:'Proposal for Urban Planning & Development',client:'NCC _ World Bank',openDate:'',closeDate:'2024-02-25',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s59',entity:'P&D',title:'Preparation of topographic survey, sub-soil investigation, Architectural & Structural Design, Detail Estimate for development and beautification with different civic facilities of Edward Park Bogura u',category:'Proposal for Urban Planning & Development',client:'Bogura Municipality',openDate:'',closeDate:'2024-01-16',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s60',entity:'P&D',title:'RFP _ Gogha ghot char bus station proposal',category:'RFP for buiding design',client:'DNCC',openDate:'',closeDate:'2024-01-16',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Max inc',value:'',startDate:'',endDate:''},
  {id:'s61',entity:'P&D',title:'Rural water, sanitation, hygiene for human development project',category:'',client:'DPHE',openDate:'',closeDate:'2023-12-26',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s62',entity:'P&D',title:'EOI _ DNCC itegrated corridor',category:'EOI for',client:'DNCC',openDate:'',closeDate:'2023-12-20',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Max inc',value:'',startDate:'',endDate:''},
  {id:'s63',entity:'P&D',title:'DSCC Asset Managmeent (DCNUP)',category:'EOI for Urban Planning & Development',client:'DSCC_ World bank',openDate:'',closeDate:'2023-12-13',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Sheltech',value:'',startDate:'',endDate:''},
  {id:'s64',entity:'P&D',title:'Feasibility Study with Conceptual Design, Cost Estimation & Draft DPP preparation for Development of ‘Children’s Park & Playground’ at Kalshi Balur Math under Dhaka North City Corporation (DNCC), Dhak',category:'EOI for park public space',client:'DNCC',openDate:'',closeDate:'2023-11-28',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with CUS',value:'',startDate:'',endDate:''},
  {id:'s65',entity:'P&D',title:'Wateraid proposal for rainwater',category:'',client:'Wateraid',openDate:'',closeDate:'2023-11-18',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s66',entity:'P&D',title:'Framework Agreement for Risk-Informed Land Use Planning Services',category:'Proposal for Urban Planning & Development',client:'Mott Mackdonald',openDate:'',closeDate:'2023-11-02',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'Individual Consultant: Farhana Rashid',value:'',startDate:'',endDate:''},
  {id:'s67',entity:'P&D',title:'Proposal for risk assessment frame work_WB_ with MOTT',category:'',client:'',openDate:'',closeDate:'2023-10-31',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s68',entity:'P&D',title:'WASH System Building Block Assessment',category:'RFP for Research_Sanitation',client:'Wateraid',openDate:'',closeDate:'2023-10-11',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s69',entity:'P&D',title:'Eoi for SNV solod waste business model',category:'',client:'SNV',openDate:'',closeDate:'2023-09-26',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s70',entity:'P&D',title:'Preparation of Architectural, Structural  Design & Drawing for Baparipara park in Narayangonj City Corporation in Ward no-16',category:'RFP for park public space',client:'NCC',openDate:'',closeDate:'2023-09-12',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s71',entity:'P&D',title:'Consultancy Service for Feasibility Study, Detailed Design, Preparation of Development Project Proposal (DPP) for Park & Lake Development with Children Play Area and Different Civic Facilities on RAJU',category:'RFP for park public space',client:'RAJUK',openDate:'',closeDate:'2023-09-03',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'JV with Sheltech',value:'',startDate:'',endDate:''},
  {id:'s72',entity:'P&D',title:'WASH Sector Landscape Study in Bangladesh',category:'',client:'Water.org',openDate:'',closeDate:'2023-08-10',status:'Submitted',result:'Rejected',responsible:'Bilash',contract:'',remark:'Link',value:'',startDate:'',endDate:''},
  {id:'s73',entity:'P&D',title:'Raj WASA feasibility',category:'',client:'Unicef',openDate:'',closeDate:'2023-07-30',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'JV with Esolve',value:'',startDate:'',endDate:''},
  {id:'s74',entity:'P&D',title:'Unicef Wsh Fit_wash facility in the hospital',category:'',client:'Unicef',openDate:'',closeDate:'2023-06-11',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'with bilash',value:'',startDate:'',endDate:''},
  {id:'s75',entity:'P&D',title:'LGED UGIP individual consultant',category:'',client:'Sheltech',openDate:'',closeDate:'2023-06-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s76',entity:'P&D',title:'Water aid potenga',category:'',client:'',openDate:'',closeDate:'2023-05-02',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s77',entity:'P&D',title:'Consultancy service for residence interior design and construction management projects',category:'Proposal for interior',client:'Mr. Sunjib Kumer Singha',openDate:'',closeDate:'2023-05-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s78',entity:'P&D',title:'Consultancy Services for the Preparation of architectural, structural Design of a G+6 multi-storied residential building at Purbachal Model Town, Dhaka',category:'Proposal for building design',client:'Advocate Pervejul Islam',openDate:'',closeDate:'2023-03-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s79',entity:'P&D',title:'Preparation of Master and Landscaping Plan of Bangladesh Academy for Rural Development (BARD), Cumilla under Bangladesh Academy for Rural Development Modernization Project',category:'RFP for Urban Planning & Development',client:'BARD',openDate:'',closeDate:'2021-11-07',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'JV with DCON',value:'',startDate:'',endDate:''},
  {id:'s80',entity:'P&D',title:'Consultancy Services for Preparation of Master Plan for Shayma Sundari Canal Redevelopment Project, Rangpur.',category:'Proposal for Urban Planning & Development',client:'RpCC',openDate:'',closeDate:'2021-09-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'JV with DCON',value:'',startDate:'',endDate:''},
  {id:'s81',entity:'P&D',title:'Consultancy service for Architectural, structural and landscape design of a two Storied residential building at Barishal',category:'Proposal for interior',client:'Rowshan Mumtaz',openDate:'',closeDate:'2020-01-01',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s82',entity:'P&D',title:'Child friendly Play space_Save the children',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s83',entity:'P&D',title:'Mr Shariful Residence projects',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s84',entity:'P&D',title:'NCC G+9 storied Residential Cum Commercial building',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s85',entity:'P&D',title:'NCC Park',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s86',entity:'P&D',title:'Sathibari commercial complex rangpur',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s87',entity:'P&D',title:'Uniliver toilet renovation project',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s88',entity:'P&D',title:'Dementia Friendly Homes with BRAC',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s89',entity:'P&D',title:'Department of Botany DU',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s90',entity:'P&D',title:'Hafiz complex, sylhet',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s91',entity:'P&D',title:'Interior for Sayeed Masud',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s92',entity:'P&D',title:'Residence design of a renowned cricketer, Magura',category:'Proposal for building design',client:'Shakib All Hasan',openDate:'',closeDate:'',status:'Unable to submit',result:'',responsible:'',contract:'',remark:'Rejected due to political issue',value:'',startDate:'',endDate:''},
  {id:'s93',entity:'P&D',title:'Residence Golam Kibria',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s94',entity:'P&D',title:'Residence Major AkiK',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s95',entity:'P&D',title:'Sylhel hospital',category:'',client:'',openDate:'',closeDate:'',status:'Submitted',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s96',entity:'P&D',title:'Interior Work of Rest house at Gazipur',category:'Proposal',client:'Mr. Waliullah',openDate:'2026-07-07',closeDate:'2026-07-31',status:'Yet to be submitted',result:'',responsible:'',contract:'',remark:'Client will share a date and time to conduct initial meeting. Currently he is out of country',value:'',startDate:'',endDate:''},
  {id:'s97',entity:'P&D',title:'brac limb centre',category:'Proposal',client:'BRAC',openDate:'2026-07-20',closeDate:'2026-07-26',status:'Yet to be submitted',result:'',responsible:'',contract:'',remark:'16072026_prarticipated pre bid meeting | with Sobuj bhai, BOQ , CAT file was collected to draft and submit proposal by 26th july 2026',value:'',startDate:'',endDate:''},
  {id:'s98',entity:'P&D',title:'Feasibility study project for the planned housing development in Gazipur district, comprising three projects over an area of more than 200 acres and eight projects within 20 acres. (7 may 2026)',category:'eGP (REOI) -> Re-tender',client:'Gazipur Development Authority',openDate:'',closeDate:'',status:'Drop',result:'',responsible:'Khairul',contract:'',remark:'Need to check the submission date for feasibility',value:'',startDate:'',endDate:''},
  {id:'s99',entity:'FM',title:'Facility Management',category:'',client:'Shanta Group',openDate:'2026-06-21',closeDate:'2026-07-31',status:'',result:'',responsible:'',contract:'',remark:'040726_Expecting conduct primary meeting by 8th July 2026 | initiated following up to inform about our services',value:'',startDate:'',endDate:''},
  {id:'s100',entity:'FM',title:'Strategy partnership',category:'Meeting',client:'IIFC',openDate:'2026-06-28',closeDate:'2026-07-31',status:'',result:'',responsible:'Farhana Apu',contract:'',remark:'050726_need to follow up Farhana Ma\'am | Conducting a meeting to explore possible scope of works',value:'',startDate:'',endDate:''},
  {id:'s101',entity:'FM',title:'Chefs Table (gulshan & Airport)',category:'Meeting',client:'Unimart',openDate:'2026-07-02',closeDate:'2026-07-09',status:'Yet to be submitted',result:'',responsible:'',contract:'',remark:'020726_we found a connection(floor incharge) to discussion | about manpower support via bhumijo FS channel. Requested to visit on thursday after lunch time to scope out the opportunites',value:'',startDate:'',endDate:''},
  {id:'s102',entity:'FM',title:'MP Hostel & Parlament Canteen',category:'Proposal',client:'',openDate:'2026-04-01',closeDate:'2026-06-30',status:'Hold',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Riaz Bhai will share update ASAP. Need to follow up on june 2026',value:'',startDate:'',endDate:''},
  {id:'s103',entity:'FM',title:'Facility management support for house and others',category:'',client:'Akik Sir',openDate:'2026-06-01',closeDate:'2026-06-30',status:'Hold',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s104',entity:'FM',title:'BUET',category:'Initial Meeting',client:'',openDate:'2026-06-01',closeDate:'2026-06-30',status:'',result:'',responsible:'Farhana Apu',contract:'',remark:'contact with DSW',value:'',startDate:'',endDate:''},
  {id:'s105',entity:'FM',title:'Biman Bangladesh',category:'Initial Meeting',client:'',openDate:'2026-06-01',closeDate:'2026-06-30',status:'',result:'',responsible:'Farhana Apu',contract:'',remark:'strategy: Lets explore and try to place brands via CSR channel to do | facility management service without taking any free from biman bangladesh',value:'',startDate:'',endDate:''},
  {id:'s106',entity:'FM',title:'Invitation for Tender- Supply of Manpower through Outsourcing Policy and Cleaning Equipment (Rental Basis) for Depot Area under DMTCL',category:'Proposal (JV)',client:'DMTCL',openDate:'2026-06-09',closeDate:'2026-06-29',status:'Submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'240626_Need to provide 300 cv for cleaner and securtiy maintainance purpose | will go for JV with VX services',value:'',startDate:'',endDate:''},
  {id:'s107',entity:'FM',title:'পুলিশ স্টাফ কলেজ বাংলাদেশ-এর আউটসোসিং পদ্ধতিতে জনবল সরবরাহ টেন্ডার সংক্রান্ত (OTM)',category:'EOI',client:'Police Staff College Bangladesh',openDate:'2026-06-16',closeDate:'2026-06-24',status:'Unable to submit',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'230626_due to lack of submission time. we are dropping this tender | follow up akik bhai',value:'',startDate:'',endDate:''},
  {id:'s108',entity:'FM',title:'Deep cleaning service',category:'Proposal',client:'Hasina apa',openDate:'2026-06-21',closeDate:'2026-06-24',status:'',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Service has been completed successfully. waiting for customer feedback',value:'',startDate:'',endDate:''},
  {id:'s109',entity:'FM',title:'EXIM Bank (Combined Islami bank)',category:'',client:'',openDate:'',closeDate:'2026-06-23',status:'Yet to be submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Need to make an offer to Mr. Skawkat (administrator).',value:'',startDate:'',endDate:''},
  {id:'s110',entity:'FM',title:'Tea Server for the Advance Dental & Implant Hospital',category:'Proposal',client:'The Advance Dental & Implant Hospital',openDate:'2026-06-16',closeDate:'2026-06-23',status:'Submitted',result:'Accepted',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'05072026_ proposal has been accepted. Effective july 2026 | 040726_revised proposal has been shared (BDT 13,500 including our SC for per person) | 270626_Budget for manpower is not approved yet by the client | proposal submitted. waiting for client response',value:'',startDate:'',endDate:''},
  {id:'s111',entity:'FM',title:'CHEZ DE SOFIA',category:'Proposal',client:'Zaved Bhai',openDate:'2026-05-01',closeDate:'2026-06-09',status:'Submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'280626_notify mokbul bhai to follow up zaved bhai, regaarding their society meeting expected to held on 3rd or 4th july 2026. need to be part of that session | 110626_Proposal submitted. Waiting for client response | Building management proposal',value:'',startDate:'',endDate:''},
  {id:'s112',entity:'FM',title:'New Club at Uttara',category:'Proposal',client:'Mr. Parvez',openDate:'2026-04-27',closeDate:'2026-06-08',status:'Submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'230626_two clearners were appointed. Agreement signing is still due | 180626_Client confirmed to deploy 2 cleaners for now. also requested to review comission. suggested to keep at 5% | 100626_Proposal submitted. waiting for client response | 030626_had a meeting with CEO, collected primary data for requirement | 110526_follow up update_Client will be share the POC details for further proceeding | 290426_Had a short conversation via phone_ Currently the main contact person is out of city. they w',value:'',startDate:'',endDate:''},
  {id:'s113',entity:'FM',title:'Deep Cleaning Service',category:'',client:'Lipi apa (Banani DOHS)',openDate:'2026-06-01',closeDate:'2026-06-01',status:'Yet to be submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'follow up by end of this month',value:'',startDate:'',endDate:''},
  {id:'s114',entity:'FM',title:'Support Staff for Parliament House Canteen',category:'Proposal',client:'Parliament House/ Toha Resturent',openDate:'2026-04-26',closeDate:'2026-05-14',status:'Submitted',result:'',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Canteen service has not started yet. | Proposal has been shared with client via whatsapp channel on 11th may 2026',value:'',startDate:'',endDate:''},
  {id:'s115',entity:'FM',title:'Unimart Sylhet',category:'Proposal',client:'United Group',openDate:'2026-04-20',closeDate:'2026-05-14',status:'Submitted',result:'Rejected',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'mail sent on may 6th. waiting for client reply. | mail sub: Proposal for Facility Cleaning Services and Supply of Materials at Playard Sylhet. | 060626_They will be deploying in house employees',value:'',startDate:'',endDate:''},
  {id:'s116',entity:'FM',title:'Aircraft cargo cleaning',category:'',client:'',openDate:'',closeDate:'2026-05-13',status:'Hold',result:'',responsible:'',contract:'',remark:'070626_need to follow up Akik Sir',value:'',startDate:'',endDate:''},
  {id:'s117',entity:'FM',title:'The Executive Kitchen',category:'Proposal',client:'Omar',openDate:'2026-04-01',closeDate:'2026-05-11',status:'Submitted',result:'Accepted',responsible:'Mokbul Bhai and Amenul',contract:'Yes',remark:'250626_Agreement signing is completed | 7th April, project start date. Need to complete contract within May 15th 2026',value:'',startDate:'',endDate:''},
  {id:'s118',entity:'FM',title:'Caritas Bangladesh',category:'Proposal',client:'7 Cleaner',openDate:'',closeDate:'2026-05-10',status:'Submitted',result:'Rejected',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'pay order collection done',value:'',startDate:'',endDate:''},
  {id:'s119',entity:'FM',title:'Deep Cleaning Sofa, Carpet & Kitchen',category:'Adhoc',client:'Orchita',openDate:'2026-03-01',closeDate:'2026-04-24',status:'Submitted',result:'Accepted',responsible:'Mokbul Bhai',contract:'Yes',remark:'Billing amount BDT 4,500 (excluding VAT & TAX',value:'',startDate:'',endDate:''},
  {id:'s120',entity:'FM',title:'Proposal for Professional Cleaning and Maintenance Services – LGED Bhaban',category:'Proposal',client:'LGED',openDate:'2026-03-12',closeDate:'2026-03-25',status:'Submitted',result:'Waiting for Result',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Ref mail: LGED. Also follow up Hamid Bhai for more work. Asssigned: Amenul',value:'',startDate:'',endDate:''},
  {id:'s121',entity:'FM',title:'Manpower Requirement for Office Support Services – Request for Proposal',category:'Proposal',client:'Emami Bangladesh',openDate:'',closeDate:'2026-03-24',status:'Submitted',result:'Rejected',responsible:'Mokbul Bhai and Amenul',contract:'',remark:'Ref mail: Manpower Requirement for Office Support Services – Request for Proposal',value:'',startDate:'',endDate:''},
  {id:'s122',entity:'FM',title:'Bi Cycle Parking Space Management at MRT Stations',category:'Financial',client:'DMTCL',openDate:'',closeDate:'2026-02-25',status:'Submitted',result:'Accepted',responsible:'',contract:'No',remark:'1 year rental advance payment along with security deposit submission is done. Contract will be signed on 11 th may 2026',value:'',startDate:'',endDate:''},
  {id:'s123',entity:'FM',title:'Dhaka Medical College and Hospital Toilet Survey (115 toilet blocks)',category:'Proposal',client:'PWD, DMCH',openDate:'',closeDate:'2025-12-17',status:'Submitted',result:'Waiting for Result',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s124',entity:'FM',title:'Quotation for External Glass & ACP Cleaning Work',category:'Proposal',client:'The Manager, Supply Chain, Le Meridien Hotel,  Nikunju, Dhaka, Bangladesh',openDate:'',closeDate:'2025-11-23',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s125',entity:'FM',title:'Cleaning Service for Talha Group - Anabil Tower and the Grand Delvistaa',category:'Proposal',client:'Talha Group',openDate:'',closeDate:'2025-11-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Current contract will expire in March, follow up from Feb',value:'',startDate:'',endDate:''},
  {id:'s126',entity:'FM',title:'Facility Cleaning Service for the Advance Dental & Implant Hospital',category:'Proposal',client:'Dr. Md. Mustafizur Rahman',openDate:'',closeDate:'2025-10-20',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s127',entity:'FM',title:'Regular Cleaning Service for Jolshiri Cantonment School and College',category:'Proposal',client:'Principal of Jolshiri Cantonment School and College',openDate:'',closeDate:'2025-10-16',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'At chairmans descision',value:'',startDate:'',endDate:''},
  {id:'s128',entity:'FM',title:'Cleaning work of various parks, playgrounds and public toilets under the jurisdiction of DNCC. (Re-Tender: 1131406)',category:'eGp - Tender: 1151263',client:'DNCC',openDate:'',closeDate:'2025-10-06',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected (highest budget issue???)',value:'',startDate:'',endDate:''},
  {id:'s129',entity:'FM',title:'Cleaning service & office support attendants at CONCERN WORLDWIDE',category:'Proposal',client:'Tariqusz Zaman, CONCERN WORLDWIDE',openDate:'',closeDate:'2025-08-26',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s130',entity:'FM',title:'Regular Cleaning Services for Brain Station 23 PLC',category:'Proposal',client:'The Head of Admin, Brain Station 23 PLC',openDate:'',closeDate:'2025-07-09',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s131',entity:'FM',title:'Toilet Management of DMCH',category:'Proposal',client:'DMCH',openDate:'',closeDate:'2025-06-30',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'follow up after election',value:'',startDate:'',endDate:''},
  {id:'s132',entity:'FM',title:'Quotation for External Glass & ACP Cleaning work',category:'Proposal',client:'The Chairman Uttara Motors Ltd',openDate:'',closeDate:'2025-06-18',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s133',entity:'FM',title:'Deep Cleaning Service in “The Royal Paradise Hotel”',category:'Proposal',client:'The General Manager Huawei, Sky Garden Hotel',openDate:'',closeDate:'2025-06-18',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s134',entity:'FM',title:'Janitorial/ Cleaning service at IUB Campus',category:'Proposal',client:'IUB',openDate:'',closeDate:'2025-05-05',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s135',entity:'FM',title:'Ceaning services for the “Sonargaon Museum Premises"',category:'Proposal',client:'Sonargaon Museum',openDate:'',closeDate:'2025-03-25',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s136',entity:'FM',title:'CHEZ DE SOFIA',category:'Proposal',client:'CHEZ DE SOFIA',openDate:'',closeDate:'2025-03-19',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'discuss with zaved bhai in december',value:'',startDate:'',endDate:''},
  {id:'s137',entity:'FM',title:'Management of  Toilet facilities at BUET',category:'Proposal',client:'BUET',openDate:'',closeDate:'2025-02-26',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'follow up after election',value:'',startDate:'',endDate:''},
  {id:'s138',entity:'FM',title:'Manpower supply to Afifa Overseas',category:'Proposal',client:'Altaf Khan',openDate:'',closeDate:'2025-02-20',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s139',entity:'FM',title:'Cleaning services to Hamim Group Cafeteria and kitchen by VX Services Limited',category:'Proposal (JV)',client:'The Managing Director VX Services Limited',openDate:'',closeDate:'2024-12-31',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s140',entity:'FM',title:'Regular Cleaning Services for “Unico Hospitals”',category:'Proposal',client:'Mr. Sazzad Hossain, GM & Head of HR',openDate:'',closeDate:'2024-10-21',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s141',entity:'FM',title:'Cleaning Services for DEKKO ISHO Group Corporate Office',category:'Proposal',client:'Israt Jahan Maria, DEKKO ISHO GROUP',openDate:'',closeDate:'2024-10-16',status:'Submitted',result:'Rejected',responsible:'',contract:'',remark:'Rejected',value:'',startDate:'',endDate:''},
  {id:'s142',entity:'FM',title:'CZD Sofiya_Glass cleaning (External) Female Manager',category:'Proposal',client:'Javed',openDate:'',closeDate:'',status:'Submitted',result:'Accepted',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s143',entity:'FM',title:'Painting Work at Parliament House',category:'Proposal',client:'Parliament House',openDate:'',closeDate:'',status:'Yet to be submitted',result:'',responsible:'',contract:'',remark:'100526_ No udpate yet | Follow up PWD website for update.',value:'',startDate:'',endDate:''},
  {id:'s144',entity:'FM',title:'Sonali Bank',category:'Proposal',client:'',openDate:'2026-04-26',closeDate:'',status:'Yet to be submitted',result:'',responsible:'',contract:'',remark:'Toilet cleaning project for their branches. Need to visit premises for case study and make a proposal',value:'',startDate:'',endDate:''},
  {id:'s145',entity:'FM',title:'BTCL',category:'Meeting',client:'Wazed Bhai',openDate:'',closeDate:'',status:'',result:'',responsible:'',contract:'',remark:'Follow up Farhana Ma\'am',value:'',startDate:'',endDate:''},
  {id:'s146',entity:'FM',title:'Unimart Mall Management',category:'Proposal',client:'Unimart',openDate:'',closeDate:'',status:'',result:'',responsible:'',contract:'',remark:'Conduct market research to find best partner to serve Mall management. | Explore china, malasiya, Thai, Srilanka, | Also try to find right person to onboard',value:'',startDate:'',endDate:''},
  {id:'s147',entity:'WASH',title:'Construction and installation of public toilets (40) and Hand Wash Point/Corner including Drinking Water (86) at public gathering places in various City Corporations and Municipalities Tender: 1305373',category:'Tender',client:'DPHE',openDate:'2026-06-29',closeDate:'2026-07-28',status:'Yet to be submitted',result:'',responsible:'Shabuj Bhai and Khairul',contract:'',remark:'080726_Experience: 10 years; ≥1 similar contract in last 10 years, value ≥ Tk 10.52 Crore; | Average Annual Turnover (Public Sector): > Tk 21.03 Crore (last 5 years, or best 5 of last 10 years); | Minimum Liquid Assets/Working Capital/Credit Line: Tk 7.01 Crore; | Minimum Tender Capacity: Tk 14.721 Crore',value:'',startDate:'',endDate:''},
  {id:'s148',entity:'WASH',title:'Procurement of Mobile Toilets (40) (Generator & Mover) Tender: 1304733',category:'Tender',client:'DPHE',openDate:'2026-06-29',closeDate:'2026-07-23',status:'Drop',result:'',responsible:'Shabuj Bhai and Khairul',contract:'',remark:'080726_Experience: 10 years; ≥1 similar contract in last 10 years, value ≥ Tk 7 Crore; | Average Annual Turnover (Public Sector): N/A; | Minimum Liquid Assets/Working Capital/Credit Line: Tk 10.90 Crore; | Minimum Tender Capacity: N/A',value:'',startDate:'',endDate:''},
  {id:'s149',entity:'WASH',title:'Railstation Toilet Management',category:'Initial meeting',client:'',openDate:'2026-06-01',closeDate:'2026-07-31',status:'',result:'',responsible:'',contract:'',remark:'',value:'',startDate:'',endDate:''},
  {id:'s150',entity:'WASH',title:'Public toilets at Cox\'s Bazar & Chapainobabgonj',category:'General',client:'DPHE & ADB',openDate:'2026-04-01',closeDate:'2026-06-23',status:'Submitted',result:'Waiting for Result',responsible:'Ismail Bhai and Amenul',contract:'',remark:'280626_Report is not ready yet. Ismail bhai is aligned about delay of report. | 180626_survey files are still being reviewed to prepare the final report | In progress | 070626_Follow up munna for the data and to present to Mancom. Ask Ismail bhai for a probable business model',value:'',startDate:'',endDate:''},
  {id:'s151',entity:'WASH',title:'হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের বহুতল কারপার্কিং-এর ৩য় তলায় নির্মিত পাবলিক টয়লেট।',category:'Tender',client:'বেসামরিক বিমান চলাচল কর্তৃপক্ষ',openDate:'2026-05-04',closeDate:'2026-05-21',status:'Submitted',result:'Rejected',responsible:'Ismail Bhai and Amenul',contract:'',remark:'Highest bid amount was 35 lac by another company',value:'',startDate:'',endDate:''},
  {id:'s152',entity:'WASH',title:'DMTCL Notice for space rental/lease of 34 public toilets located at designated locations on the platforms of 16 metrorail stations',category:'Tender',client:'DMTCL',openDate:'2026-04-08',closeDate:'2026-04-30',status:'Submitted',result:'Rejected',responsible:'Ismail Bhai and Amenul',contract:'',remark:'280626_offcial result is not provided yet. Need further validation with assigned survey team to get proper report | DMTCL authority is evaluating the documents. expected to get final result by May month 2026',value:'',startDate:'',endDate:''},
  {id:'s153',entity:'WASH',title:'Shahabuddin Park Toilet Management',category:'Proposal',client:'Gulshan Society',openDate:'2026-07-07',closeDate:'2026-07-16',status:'Submitted',result:'Waiting for Result',responsible:'Ismail Bhai and Amenul',contract:'',remark:'19072026_Proposal has been shared to Office manager and requested to give us a meeting date to showcase the presentation after 21st july 2026 | Proposal drafting is in progress',value:'',startDate:'',endDate:''},
  {id:'s154',entity:'Tech',title:'Chez De Sofia',category:'General',client:'',openDate:'2026-04-25',closeDate:'2026-05-10',status:'Yet to be submitted',result:'',responsible:'Akil And Amenul',contract:'',remark:'Update new | IP based camera montioring system for better security monitoring purpose.',value:'',startDate:'',endDate:''},
  {id:'s155',entity:'Tech',title:'Chez De Sofia',category:'General',client:'',openDate:'2026-04-01',closeDate:'2026-04-15',status:'Submitted',result:'Accepted',responsible:'Akil',contract:'Yes',remark:'Project was completed on 30th april 2026',value:'',startDate:'',endDate:''}
];;

// ─── STATE ────────────────────────────────────────────────────────────────────
const STORAGE_KEY = 'bhumijo_proposals_v8';
const CLIENTS_KEY = 'bhumijo_clients_v1';
let proposals = [];
let clients = [];
let filteredData = [];
let sortField = 'closeDate';
let sortDir = 'asc';
let currentPage = 1;
const PAGE_SIZE = 25;
let editingId = null;
let editingClientId = null;
let confirmCallback = null;
let charts = {};


// ─── SERVER CONNECTION (LAN sync via collector.py) ─────────────────────────────
const SERVER_IP_KEY = 'bhumijo_server_ip';
const SERVER_TOKEN_KEY = 'bhumijo_server_token';
let serverConnected = false;
let serverBaseUrl = '';
let serverToken = '';
let serverSyncing = false;

function init() {
  // Connecting comes FIRST and stands on its own.
  //
  // It used to be the last line here, which meant any error in the six calls
  // below silently prevented it - and the only symptom was the sidebar asking
  // for the IP and token again, with no clue why. Connecting to the server
  // does not depend on any screen having rendered, so it should never be
  // hostage to one.
  try { restoreServerConnection(); } catch (e) { console.error('auto-connect failed', e); }

  // Each of these is isolated too: one broken screen must not take the rest
  // of the page down with it.
  [loadData, renderSidebarDate, renderDashboard, filterTable,
   renderResponsibleOptions, renderCategoryOptions].forEach(function (step) {
    try { step(); } catch (e) { console.error(step.name + '() failed', e); }
  });
}

function loadData() {
  ['bhumijo_proposals_v2','bhumijo_proposals_v3','bhumijo_proposals_v4',
   'bhumijo_proposals_v5','bhumijo_proposals_v6','bhumijo_proposals_v7'].forEach(function(k){
    try{localStorage.removeItem(k);}catch(e){}
  });
  try {
    var stored = localStorage.getItem(STORAGE_KEY);
    var parsed = stored ? JSON.parse(stored) : null;
    if(!parsed || parsed.length !== SEED.length) {
      parsed = null;
      try{localStorage.removeItem(STORAGE_KEY);}catch(e){}
    }
    proposals = parsed ? parsed : SEED.map(function(p,i){return Object.assign({},p,{id:p.id||'s'+i,createdAt:p.closeDate||'2024-01-01'});});
    if(!parsed) saveData();
  } catch(e) {
    proposals = SEED.map(function(p,i){return Object.assign({},p,{id:p.id||'s'+i,createdAt:p.closeDate||'2024-01-01'});});
    saveData();
  }
  try {
    var storedC = localStorage.getItem(CLIENTS_KEY);
    clients = storedC ? JSON.parse(storedC) : buildClientsFromProposals();
    if(!storedC) saveClients();
  } catch(e) { clients = []; }
}


function hardReset() {
  if(!confirm('Reload all 156 proposals from the original Excel dataset? Manually added entries will be lost.')) return;
  ['bhumijo_proposals_v2','bhumijo_proposals_v3','bhumijo_proposals_v4',
   'bhumijo_proposals_v5','bhumijo_proposals_v6','bhumijo_proposals_v7','bhumijo_proposals_v8',
   'bhumijo_clients_v1'].forEach(function(k){try{localStorage.removeItem(k);}catch(e){}});
  proposals = SEED.map(function(p,i){return Object.assign({},p,{id:p.id||'s'+i,createdAt:p.closeDate||'2024-01-01'});});
  clients = buildClientsFromProposals();
  saveData(); saveClients();
  renderDashboard(); filterTable(); renderClients();
  toast('Reset complete. 156 proposals loaded from Excel data.','success');
}
function saveData() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(proposals)); } catch(e){} pushProposalsToServer(); }
function saveClients() { try { localStorage.setItem(CLIENTS_KEY, JSON.stringify(clients)); } catch(e){} pushClientsToServer(); }

function buildClientsFromProposals() {
  return proposals
    .filter(p => p.result === 'Accepted' && p.client && p.client.trim())
    .map(p => ({
      id: 'c_auto_' + Math.random().toString(36).substr(2,8),
      name: p.client,
      entity: p.entity,
      project: p.title,
      value: p.value||'',
      responsible: p.responsible||'',
      startDate: p.startDate||'',
      endDate: p.endDate||'',
      notes: '',
      fromProposalId: p.id,
      createdAt: p.createdAt||''
    }));
}
